[build-system]
requires = ["setuptools>=65.3.0"]
build-backend = "setuptools.build_meta"

[project]
name = "castepio"
requires-python = ">=3.8"
license = {text = "MIT License"}
classifiers = [
    "Programming Language :: Python :: 3"
]
